/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("RedemptionsObjectPageObjectPage journey");

        opaTest("Navigate to RedemptionsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheRedemptionsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheRedemptionsListGenerated.onTable().iCheckRows();
            When.onTheRedemptionsListGenerated.onTable().iPressRow(0);

            Then.onTheRedemptionsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheRedemptionsObjectPageGenerated.iCheckSection({ section: "Main" });
            Then.onTheRedemptionsObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "redeemedAmount" });
            Then.onTheRedemptionsObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "customer_ID" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});