/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PurchasesObjectPageObjectPage journey");

        opaTest("Navigate to PurchasesObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThePurchasesListGenerated.onFilterBar().iExecuteSearch();
            Then.onThePurchasesListGenerated.onTable().iCheckRows();
            When.onThePurchasesListGenerated.onTable().iPressRow(0);

            Then.onThePurchasesObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThePurchasesObjectPageGenerated.iCheckSection({ section: "Main" });
            Then.onThePurchasesObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "purchaseValue" });
            Then.onThePurchasesObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "rewardPoints" });
            Then.onThePurchasesObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "customer_ID" });
            Then.onThePurchasesObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "selectedProduct_ID" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});