/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("CustomersObjectPageObjectPage journey");

        opaTest("Navigate to CustomersObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheCustomersListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheCustomersListGenerated.onTable().iCheckRows();
            When.onTheCustomersListGenerated.onTable().iPressRow(0);

            Then.onTheCustomersObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheCustomersObjectPageGenerated.iCheckSection({ section: "Main" });
            Then.onTheCustomersObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "email" });
            Then.onTheCustomersObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "customerNumber" });
            Then.onTheCustomersObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "totalPurchaseValue" });
            Then.onTheCustomersObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "totalRewardPoints" });
            Then.onTheCustomersObjectPageGenerated.onForm({ section: "Main" }).iCheckField({ property: "totalRedeemedRewardPoints" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});